export const environment = {
    production: true,
    authUrl: 'https://api-budget.francecentral-01.azurewebsites.net/api/auth/',
    managerUrl: 'https://api-budget.francecentral-01.azurewebsites.net/api/manager/',
    uploadData: 'https://api-budget.francecentral-01.azurewebsites.net/api/training/',
    uploadBudget: 'https://api-budget.francecentral-01.azurewebsites.net/api/training/upload-budgets',
    userDataUrl: 'https://api-budget.francecentral-01.azurewebsites.net/api/user/',
    serpApiFlightUrl: 'https://api-budget.francecentral-01.azurewebsites.net/api/serpapi/flights/search',
    serpApiHotelUrl: 'https://api-budget.francecentral-01.azurewebsites.net/api/serpapi/hotels/search',
    calendarTrainingUrl: 'https://api-budget.francecentral-01.azurewebsites.net/api/user/training',
    profileUrl: 'https://api-budget.francecentral-01.azurewebsites.net/api/user/profile',
    teamMembersNameUrl: 'https://api-budget.francecentral-01.azurewebsites.net/api/user/team-members',
    exchangerateApiKey: 'cur_live_umqer7vKD6LVGydlBhhApzjGahEAG1ZIOWDKGEwV',
    missionUrl: 'https://api-budget.francecentral-01.azurewebsites.net/api/missions',
};