export const environment = {
    production: false,
    authUrl: '/api/auth/',
    managerUrl: '/api/manager/',
    uploadData: '/api/training/',
    uploadBudget: '/api/training/upload-budgets',
    userDataUrl: '/api/user/',
    serpApiFlightUrl: '/api/serpapi/flights/search',
    serpApiHotelUrl: '/api/serpapi/hotels/search',
    calendarTrainingUrl: '/api/user/training',
    profileUrl: '/api/user/profile',
    teamMembersNameUrl: '/api/user/team-members',
    exchangerateApiKey:'cur_live_xX7Dz0VNIElWlpBUH0YSkz1KOnKz8opOfh4Av3Qn',
    missionUrl : '/api/missions',
};